services:
  tunnel:
    build: tunnel
    container_name: tunnel
    cap_add:
      - NET_ADMIN
    ports:
      - "443:443"

  server:
    build: server
    container_name: server
    restart: unless-stopped
    network_mode: "service:tunnel"
  
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./server/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    network_mode: "service:tunnel"